#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# COMPONENT: absolute

#configuration
. /opt/Xilinx/Vivado/2017.4/settings64.sh >& /dev/null; 

# STEP: vivado_flow
vivado -mode batch -nojournal -nolog -source HLS_output//Synthesis/vivado_flow_0/vivado.tcl


